### ISSUE TITLE
ansible_host set to another variable fails

### ISSUE THREAD

**Issue by divansantana** [pytest-dev/pytest-testinfra#620]
Trying to use ansible connection backend, it seems to fail when
ansible_host variable is set to another variable, like so `inventories/host_vars/my_host.yml`

```yaml
---
network_interfaces:
  - name: ens3
    address: 10.254.14.18
    netmask: 255.255.255.0
    gateway: 10.254.14.1

ansible_host: "{{ network_interfaces[0]['address'] }}"
```

when running testinfra this results in:

```
E           RuntimeError: CommandResult(command=b"sudo /bin/sh -c 'getent ahosts mail.example.com'", exit_status=255, stdout=None, stderr=b"ssh: Could not resolve hostname {{ network_interfaces[0]['address'] }}: Name or service not known\r\n")
```

A workaround is changing the host inventory file like so, but this is
not ideal:

```yml
---
network_interfaces:
  - name: ens3
    address: 10.254.14.18
    netmask: 255.255.255.0
    gateway: 10.254.14.1

ansible_host: 10.254.14.18 
```

Is this a limitation in testinfra, or am I doing something wrong?

versions using:
```
Python 3.8.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
plugins: testinfra-6.4.0
ansible == 4.1.0
```
